-- Google Maps Categories (Table A from Places API)
-- Source: https://developers.google.com/maps/documentation/places/web-service/place-types

INSERT INTO categories (id, name, icon) VALUES
-- Automotive
('car_dealer', 'Car Dealer', 'i-tabler:car'),
('car_rental', 'Car Rental', 'i-tabler:car'),
('car_repair', 'Car Repair', 'i-tabler:car'),
('car_wash', 'Car Wash', 'i-tabler:car'),
('electric_vehicle_charging_station', 'Electric Vehicle Charging Station', 'i-tabler:charging-pile'),
('gas_station', 'Gas Station', 'i-tabler:gas-station'),
('parking', 'Parking', 'i-tabler:parking'),
('rest_stop', 'Rest Stop', 'i-tabler:gas-station'),

-- Business
('corporate_office', 'Corporate Office', 'i-tabler:building'),
('farm', 'Farm', 'i-tabler:tree'),
('ranch', 'Ranch', 'i-tabler:tree'),

-- Culture and Arts
('art_gallery', 'Art Gallery', 'i-tabler:palette'),
('art_studio', 'Art Studio', 'i-tabler:palette'),
('auditorium', 'Auditorium', 'i-tabler:theater'),
('cultural_landmark', 'Cultural Landmark', 'i-tabler:map-pin'),
('historical_place', 'Historical Place', 'i-tabler:map-pin'),
('monument', 'Monument', 'i-tabler:map-pin'),
('museum', 'Museum', 'i-tabler:palette'),
('performing_arts_theater', 'Performing Arts Theater', 'i-tabler:masks-theater'),
('sculpture', 'Sculpture', 'i-tabler:palette'),

-- Education
('library', 'Library', 'i-tabler:book'),
('preschool', 'Preschool', 'i-tabler:school'),
('primary_school', 'Primary School', 'i-tabler:school'),
('school', 'School', 'i-tabler:school'),
('secondary_school', 'Secondary School', 'i-tabler:school'),
('university', 'University', 'i-tabler:school'),

-- Entertainment and Recreation
('adventure_sports_center', 'Adventure Sports Center', 'i-tabler:trophy'),
('amphitheatre', 'Amphitheatre', 'i-tabler:building-stadium'),
('amusement_center', 'Amusement Center', 'i-tabler:device-gamepad-2'),
('amusement_park', 'Amusement Park', 'i-tabler:roller-skating'),
('aquarium', 'Aquarium', 'i-tabler:fish'),
('banquet_hall', 'Banquet Hall', 'i-tabler:building'),
('barbecue_area', 'Barbecue Area', 'i-tabler:meat'),
('botanical_garden', 'Botanical Garden', 'i-tabler:tree'),
('bowling_alley', 'Bowling Alley', 'i-tabler:bowling'),
('casino', 'Casino', 'i-tabler:cards'),
('childrens_camp', 'Childrens Camp', 'i-tabler:tent'),
('comedy_club', 'Comedy Club', 'i-tabler:mood-smile'),
('community_center', 'Community Center', 'i-tabler:users'),
('concert_hall', 'Concert Hall', 'i-tabler:microphone-2'),
('convention_center', 'Convention Center', 'i-tabler:building'),
('cultural_center', 'Cultural Center', 'i-tabler:building'),
('cycling_park', 'Cycling Park', 'i-tabler:bike'),
('dance_hall', 'Dance Hall', 'i-tabler:music'),
('dog_park', 'Dog Park', 'i-tabler:tree'),
('event_venue', 'Event Venue', 'i-tabler:building'),
('ferris_wheel', 'Ferris Wheel', 'i-tabler:circle-dashed'),
('garden', 'Garden', 'i-tabler:tree'),
('hiking_area', 'Hiking Area', 'i-tabler:tree'),
('historical_landmark', 'Historical Landmark', 'i-tabler:map-pin'),
('internet_cafe', 'Internet Cafe', 'i-tabler:coffee'),
('karaoke', 'Karaoke', 'i-tabler:music'),
('marina', 'Marina', 'i-tabler:beach'),
('movie_rental', 'Movie Rental', 'i-tabler:movie'),
('movie_theater', 'Movie Theater', 'i-tabler:movie'),
('national_park', 'National Park', 'i-tabler:tree'),
('night_club', 'Night Club', 'i-tabler:beer'),
('observation_deck', 'Observation Deck', 'i-tabler:building-skyscraper'),
('off_roading_area', 'Off Roading Area', 'i-tabler:car'),
('opera_house', 'Opera House', 'i-tabler:masks-theater'),
('park', 'Park', 'i-tabler:tree'),
('philharmonic_hall', 'Philharmonic Hall', 'i-tabler:music'),
('picnic_ground', 'Picnic Ground', 'i-tabler:tree'),
('planetarium', 'Planetarium', 'i-tabler:building'),
('plaza', 'Plaza', 'i-tabler:map-pin'),
('roller_coaster', 'Roller Coaster', 'i-tabler:timeline'),
('skateboard_park', 'Skateboard Park', 'i-tabler:bike'),
('state_park', 'State Park', 'i-tabler:tree'),
('tourist_attraction', 'Tourist Attraction', 'i-tabler:map-pin'),
('video_arcade', 'Video Arcade', 'i-tabler:device-gamepad'),
('visitor_center', 'Visitor Center', 'i-tabler:map-pin'),
('water_park', 'Water Park', 'i-tabler:pool'),
('wedding_venue', 'Wedding Venue', 'i-tabler:building'),
('wildlife_park', 'Wildlife Park', 'i-tabler:tree'),
('wildlife_refuge', 'Wildlife Refuge', 'i-tabler:tree'),
('zoo', 'Zoo', 'i-tabler:tree'),

-- Facilities
('public_bath', 'Public Bath', 'i-tabler:bath'),
('public_bathroom', 'Public Bathroom', 'i-tabler:toilet-paper'),
('stable', 'Stable', 'i-tabler:tree'),

-- Finance
('accounting', 'Accounting', 'i-tabler:coins'),
('atm', 'ATM', 'i-tabler:coins'),
('bank', 'Bank', 'i-tabler:building-bank'),

-- Food and Drink
('acai_shop', 'Acai Shop', 'i-tabler:ice-cream'),
('afghani_restaurant', 'Afghani Restaurant', 'i-tabler:soup'),
('african_restaurant', 'African Restaurant', 'i-tabler:chef-hat'),
('american_restaurant', 'American Restaurant', 'i-tabler:pizza'),
('asian_restaurant', 'Asian Restaurant', 'i-tabler:bowl'),
('bagel_shop', 'Bagel Shop', 'i-tabler:coffee'),
('bakery', 'Bakery', 'i-tabler:cake'),
('bar', 'Bar', 'i-tabler:beer'),
('bar_and_grill', 'Bar And Grill', 'i-tabler:beer'),
('barbecue_restaurant', 'Barbecue Restaurant', 'i-tabler:meat'),
('brazilian_restaurant', 'Brazilian Restaurant', 'i-tabler:meat'),
('breakfast_restaurant', 'Breakfast Restaurant', 'i-tabler:egg'),
('brunch_restaurant', 'Brunch Restaurant', 'i-tabler:coffee'),
('buffet_restaurant', 'Buffet Restaurant', 'i-tabler:tools-kitchen-2'),
('cafe', 'Cafe', 'i-tabler:coffee'),
('cafeteria', 'Cafeteria', 'i-tabler:coffee'),
('candy_store', 'Candy Store', 'i-tabler:ice-cream'),
('cat_cafe', 'Cat Cafe', 'i-tabler:coffee'),
('chinese_restaurant', 'Chinese Restaurant', 'i-tabler:bowl'),
('chocolate_factory', 'Chocolate Factory', 'i-tabler:ice-cream'),
('chocolate_shop', 'Chocolate Shop', 'i-tabler:ice-cream'),
('coffee_shop', 'Coffee Shop', 'i-tabler:coffee'),
('confectionery', 'Confectionery', 'i-tabler:cake'),
('deli', 'Deli', 'i-tabler:bread'),
('dessert_restaurant', 'Dessert Restaurant', 'i-tabler:ice-cream'),
('dessert_shop', 'Dessert Shop', 'i-tabler:ice-cream'),
('diner', 'Diner', 'i-tabler:tools-kitchen-2'),
('dog_cafe', 'Dog Cafe', 'i-tabler:coffee'),
('donut_shop', 'Donut Shop', 'i-tabler:cake'),
('fast_food_restaurant', 'Fast Food Restaurant', 'i-tabler:pizza'),
('fine_dining_restaurant', 'Fine Dining Restaurant', 'i-tabler:chef-hat'),
('food_court', 'Food Court', 'i-tabler:tools-kitchen-2'),
('french_restaurant', 'French Restaurant', 'i-tabler:chef-hat'),
('greek_restaurant', 'Greek Restaurant', 'i-tabler:lemon'),
('hamburger_restaurant', 'Hamburger Restaurant', 'i-tabler:burger'),
('ice_cream_shop', 'Ice Cream Shop', 'i-tabler:ice-cream'),
('indian_restaurant', 'Indian Restaurant', 'i-tabler:bowl'),
('indonesian_restaurant', 'Indonesian Restaurant', 'i-tabler:soup'),
('italian_restaurant', 'Italian Restaurant', 'i-tabler:pizza'),
('japanese_restaurant', 'Japanese Restaurant', 'i-tabler:fish'),
('juice_shop', 'Juice Shop', 'i-tabler:coffee'),
('korean_restaurant', 'Korean Restaurant', 'i-tabler:bowl'),
('lebanese_restaurant', 'Lebanese Restaurant', 'i-tabler:soup'),
('meal_delivery', 'Meal Delivery', 'i-tabler:bike'),
('meal_takeaway', 'Meal Takeaway', 'i-tabler:shopping-bag'),
('mediterranean_restaurant', 'Mediterranean Restaurant', 'i-tabler:lemon'),
('mexican_restaurant', 'Mexican Restaurant', 'i-tabler:pepper'),
('middle_eastern_restaurant', 'Middle Eastern Restaurant', 'i-tabler:soup'),
('pizza_restaurant', 'Pizza Restaurant', 'i-tabler:pizza'),
('pub', 'Pub', 'i-tabler:beer'),
('ramen_restaurant', 'Ramen Restaurant', 'i-tabler:bowl'),
('restaurant', 'Restaurant', 'i-tabler:tools-kitchen-2'),
('sandwich_shop', 'Sandwich Shop', 'i-tabler:bread'),
('seafood_restaurant', 'Seafood Restaurant', 'i-tabler:fish'),
('spanish_restaurant', 'Spanish Restaurant', 'i-tabler:chef-hat'),
('steak_house', 'Steak House', 'i-tabler:meat'),
('sushi_restaurant', 'Sushi Restaurant', 'i-tabler:fish'),
('tea_house', 'Tea House', 'i-tabler:coffee'),
('thai_restaurant', 'Thai Restaurant', 'i-tabler:bowl'),
('turkish_restaurant', 'Turkish Restaurant', 'i-tabler:soup'),
('vegan_restaurant', 'Vegan Restaurant', 'i-tabler:salad'),
('vegetarian_restaurant', 'Vegetarian Restaurant', 'i-tabler:salad'),
('vietnamese_restaurant', 'Vietnamese Restaurant', 'i-tabler:bowl'),
('wine_bar', 'Wine Bar', 'i-tabler:beer'),

-- Government
('city_hall', 'City Hall', 'i-tabler:building'),
('courthouse', 'Courthouse', 'i-tabler:gavel'),
('embassy', 'Embassy', 'i-tabler:building'),
('fire_station', 'Fire Station', 'i-tabler:building'),
('government_office', 'Government Office', 'i-tabler:building'),
('local_government_office', 'Local Government Office', 'i-tabler:building'),
('neighborhood_police_station', 'Neighborhood Police Station', 'i-tabler:building'),
('police', 'Police', 'i-tabler:building'),
('post_office', 'Post Office', 'i-tabler:building'),

-- Health and Wellness
('chiropractor', 'Chiropractor', 'i-tabler:massage'),
('dental_clinic', 'Dental Clinic', 'i-tabler:pill'),
('dentist', 'Dentist', 'i-tabler:pill'),
('doctor', 'Doctor', 'i-tabler:vaccine'),
('drugstore', 'Drugstore', 'i-tabler:pill'),
('hospital', 'Hospital', 'i-tabler:vaccine'),
('massage', 'Massage', 'i-tabler:massage'),
('medical_lab', 'Medical Lab', 'i-tabler:vaccine'),
('pharmacy', 'Pharmacy', 'i-tabler:pill'),
('physiotherapist', 'Physiotherapist', 'i-tabler:massage'),
('sauna', 'Sauna', 'i-tabler:bath'),
('skin_care_clinic', 'Skin Care Clinic', 'i-tabler:massage'),
('spa', 'Spa', 'i-tabler:bath'),
('tanning_studio', 'Tanning Studio', 'i-tabler:massage'),
('wellness_center', 'Wellness Center', 'i-tabler:massage'),
('yoga_studio', 'Yoga Studio', 'i-tabler:massage'),

-- Lodging
('bed_and_breakfast', 'Bed And Breakfast', 'i-tabler:bed'),
('budget_japanese_inn', 'Budget Japanese Inn', 'i-tabler:bed'),
('campground', 'Campground', 'i-tabler:tent'),
('camping_cabin', 'Camping Cabin', 'i-tabler:tent'),
('cottage', 'Cottage', 'i-tabler:home'),
('extended_stay_hotel', 'Extended Stay Hotel', 'i-tabler:bed'),
('farmstay', 'Farmstay', 'i-tabler:home'),
('guest_house', 'Guest House', 'i-tabler:bed'),
('hostel', 'Hostel', 'i-tabler:bed'),
('hotel', 'Hotel', 'i-tabler:bed'),
('inn', 'Inn', 'i-tabler:bed'),
('japanese_inn', 'Japanese Inn', 'i-tabler:bed'),
('lodging', 'Lodging', 'i-tabler:bed'),
('mobile_home_park', 'Mobile Home Park', 'i-tabler:home'),
('motel', 'Motel', 'i-tabler:bed'),
('private_guest_room', 'Private Guest Room', 'i-tabler:bed'),
('resort_hotel', 'Resort Hotel', 'i-tabler:bed'),
('rv_park', 'RV Park', 'i-tabler:parking'),

-- Places of Worship
('church', 'Church', 'i-tabler:building-church'),
('hindu_temple', 'Hindu Temple', 'i-tabler:om'),
('mosque', 'Mosque', 'i-tabler:building-mosque'),
('synagogue', 'Synagogue', 'i-tabler:star'),

-- Services
('astrologer', 'Astrologer', 'i-tabler:briefcase'),
('barber_shop', 'Barber Shop', 'i-tabler:cut'),
('beautician', 'Beautician', 'i-tabler:cut'),
('beauty_salon', 'Beauty Salon', 'i-tabler:cut'),
('body_art_service', 'Body Art Service', 'i-tabler:palette'),
('catering_service', 'Catering Service', 'i-tabler:chef-hat'),
('cemetery', 'Cemetery', 'i-tabler:map-pin'),
('child_care_agency', 'Child Care Agency', 'i-tabler:school'),
('consultant', 'Consultant', 'i-tabler:briefcase'),
('courier_service', 'Courier Service', 'i-tabler:briefcase'),
('electrician', 'Electrician', 'i-tabler:briefcase'),
('florist', 'Florist', 'i-tabler:gift'),
('food_delivery', 'Food Delivery', 'i-tabler:bike'),
('foot_care', 'Foot Care', 'i-tabler:massage'),
('funeral_home', 'Funeral Home', 'i-tabler:building'),
('hair_care', 'Hair Care', 'i-tabler:cut'),
('hair_salon', 'Hair Salon', 'i-tabler:cut'),
('insurance_agency', 'Insurance Agency', 'i-tabler:briefcase'),
('laundry', 'Laundry', 'i-tabler:hanger'),
('lawyer', 'Lawyer', 'i-tabler:gavel'),
('locksmith', 'Locksmith', 'i-tabler:briefcase'),
('makeup_artist', 'Makeup Artist', 'i-tabler:cut'),
('moving_company', 'Moving Company', 'i-tabler:briefcase'),
('nail_salon', 'Nail Salon', 'i-tabler:cut'),
('painter', 'Painter', 'i-tabler:palette'),
('plumber', 'Plumber', 'i-tabler:briefcase'),
('psychic', 'Psychic', 'i-tabler:briefcase'),
('real_estate_agency', 'Real Estate Agency', 'i-tabler:building'),
('roofing_contractor', 'Roofing Contractor', 'i-tabler:briefcase'),
('storage', 'Storage', 'i-tabler:building'),
('summer_camp_organizer', 'Summer Camp Organizer', 'i-tabler:tent'),
('tailor', 'Tailor', 'i-tabler:hanger'),
('telecommunications_service_provider', 'Telecommunications Service Provider', 'i-tabler:device-mobile'),
('tour_agency', 'Tour Agency', 'i-tabler:map-pin'),
('tourist_information_center', 'Tourist Information Center', 'i-tabler:map-pin'),
('travel_agency', 'Travel Agency', 'i-tabler:plane'),
('veterinary_care', 'Veterinary Care', 'i-tabler:briefcase'),

-- Shopping
('asian_grocery_store', 'Asian Grocery Store', 'i-tabler:shopping-bag'),
('auto_parts_store', 'Auto Parts Store', 'i-tabler:car'),
('bicycle_store', 'Bicycle Store', 'i-tabler:bike'),
('book_store', 'Book Store', 'i-tabler:book'),
('butcher_shop', 'Butcher Shop', 'i-tabler:meat'),
('cell_phone_store', 'Cell Phone Store', 'i-tabler:device-mobile'),
('clothing_store', 'Clothing Store', 'i-tabler:shirt'),
('convenience_store', 'Convenience Store', 'i-tabler:shopping-bag'),
('department_store', 'Department Store', 'i-tabler:shopping-bag'),
('discount_store', 'Discount Store', 'i-tabler:shopping-bag'),
('electronics_store', 'Electronics Store', 'i-tabler:device-mobile'),
('food_store', 'Food Store', 'i-tabler:shopping-bag'),
('furniture_store', 'Furniture Store', 'i-tabler:home'),
('gift_shop', 'Gift Shop', 'i-tabler:gift'),
('grocery_store', 'Grocery Store', 'i-tabler:shopping-bag'),
('hardware_store', 'Hardware Store', 'i-tabler:briefcase'),
('home_goods_store', 'Home Goods Store', 'i-tabler:home'),
('home_improvement_store', 'Home Improvement Store', 'i-tabler:home'),
('jewelry_store', 'Jewelry Store', 'i-tabler:gift'),
('liquor_store', 'Liquor Store', 'i-tabler:beer'),
('market', 'Market', 'i-tabler:shopping-bag'),
('pet_store', 'Pet Store', 'i-tabler:shopping-bag'),
('shoe_store', 'Shoe Store', 'i-tabler:shirt'),
('shopping_mall', 'Shopping Mall', 'i-tabler:shopping-bag'),
('sporting_goods_store', 'Sporting Goods Store', 'i-tabler:barbell'),
('store', 'Store', 'i-tabler:shopping-bag'),
('supermarket', 'Supermarket', 'i-tabler:shopping-bag'),
('warehouse_store', 'Warehouse Store', 'i-tabler:building'),
('wholesaler', 'Wholesaler', 'i-tabler:shopping-bag'),

-- Sports and Fitness
('arena', 'Arena', 'i-tabler:trophy'),
('athletic_field', 'Athletic Field', 'i-tabler:trophy'),
('fishing_charter', 'Fishing Charter', 'i-tabler:beach'),
('fishing_pond', 'Fishing Pond', 'i-tabler:beach'),
('fitness_center', 'Fitness Center', 'i-tabler:barbell'),
('golf_course', 'Golf Course', 'i-tabler:trophy'),
('gym', 'Gym', 'i-tabler:barbell'),
('ice_skating_rink', 'Ice Skating Rink', 'i-tabler:trophy'),
('playground', 'Playground', 'i-tabler:tree'),
('ski_resort', 'Ski Resort', 'i-tabler:trophy'),
('sports_activity_location', 'Sports Activity Location', 'i-tabler:trophy'),
('sports_club', 'Sports Club', 'i-tabler:trophy'),
('sports_coaching', 'Sports Coaching', 'i-tabler:trophy'),
('sports_complex', 'Sports Complex', 'i-tabler:trophy'),
('stadium', 'Stadium', 'i-tabler:trophy'),
('swimming_pool', 'Swimming Pool', 'i-tabler:beach'),

-- Transportation
('airport', 'Airport', 'i-tabler:plane'),
('airstrip', 'Airstrip', 'i-tabler:plane'),
('bus_station', 'Bus Station', 'i-tabler:bus'),
('bus_stop', 'Bus Stop', 'i-tabler:bus'),
('ferry_terminal', 'Ferry Terminal', 'i-tabler:beach'),
('heliport', 'Heliport', 'i-tabler:plane'),
('international_airport', 'International Airport', 'i-tabler:plane'),
('light_rail_station', 'Light Rail Station', 'i-tabler:train'),
('park_and_ride', 'Park And Ride', 'i-tabler:parking'),
('subway_station', 'Subway Station', 'i-tabler:train'),
('taxi_stand', 'Taxi Stand', 'i-tabler:car'),
('train_station', 'Train Station', 'i-tabler:train'),
('transit_depot', 'Transit Depot', 'i-tabler:bus'),
('transit_station', 'Transit Station', 'i-tabler:train'),
('truck_stop', 'Truck Stop', 'i-tabler:gas-station'),

-- Geographic Areas
('administrative_area_level_1', 'Administrative Area Level 1', 'i-tabler:map-pin'),
('administrative_area_level_2', 'Administrative Area Level 2', 'i-tabler:map-pin'),
('country', 'Country', 'i-tabler:map-pin'),
('locality', 'Locality', 'i-tabler:map-pin'),
('postal_code', 'Postal Code', 'i-tabler:map-pin'),
('school_district', 'School District', 'i-tabler:school'),

-- Residential
('apartment_building', 'Apartment Building', 'i-tabler:building'),
('apartment_complex', 'Apartment Complex', 'i-tabler:building'),
('condominium_complex', 'Condominium Complex', 'i-tabler:building'),
('housing_complex', 'Housing Complex', 'i-tabler:building'),

-- Other
('beach', 'Beach', 'i-tabler:beach')

ON CONFLICT (id) DO NOTHING;
