catalog:
  '@iconify-json/flag': ^1.2.10
  '@protomaps/basemaps': ^5.7.0
  '@vueuse/core': ^13.8.0
  zod: ^3.25.56

catalogs:
  database:
    '@electric-sql/pglite': ^0.3.14
    drizzle-kit: ^0.31.7
    drizzle-orm: ^0.44.7
    postgres: ^3.4.7
  dev:
    '@antfu/eslint-config': ^6.2.0
    '@iconify-json/tabler': ^1.2.23
    '@nuxt/eslint': ^1.10.0
    '@unocss/eslint-plugin': ^66.5.9
    dotenv: ^17.2.3
    eslint: ^9.39.1
    eslint-plugin-format: ^1.0.2
    tsx: ^4.20.6
    typescript: ^5.9.3
    wrangler: ^4.51.0
  framework:
    '@nuxt/fonts': ^0.12.1
    '@nuxt/icon': ^2.1.0
    '@nuxthub/core': npm:@nuxthub/core-nightly@0.10.0-20251205-001323-943b30c
    '@nuxtjs/i18n': ^10.2.1
    '@vueuse/nuxt': ^13.8.0
    '@vueuse/router': ^13.8.0
    nuxt: ^4.2.1
    nuxt-maplibre: ^1.2.0
    nuxt-safe-runtime-config: ^0.0.10
  test:
    '@nuxt/test-utils': ^3.20.1
    '@vue/test-utils': ^2.4.6
    happy-dom: ^20.0.10
    playwright-core: ^1.57.0
    vitest: ^4.0.14
  ui:
    '@unocss/nuxt': ^66.5.9
    maplibre-gl: ^5.13.0
    motion-v: ^1.7.4
    nimiq-css: ^1.0.0-beta.146
    nimiq-flags: ^1.0.0-beta.146
    nimiq-icons: ^1.0.0-beta.146
    reka-ui: ^2.6.0
    unocss: ^66.5.9
    unocss-preset-onmax: 1.0.0-beta.52
    vaul-vue: ^0.4.1
    vue-sonner: ^2.0.9
  utils:
    '@ai-sdk/openai': ^2.0.73
    ai: ^5.0.102
    consola: ^3.4.2
    date-fns: ^4.1.0
    date-fns-tz: ^3.2.0
    opening_hours: ^3.9.0
    pathe: ^2.0.3
    valibot: ^1.2.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
  - workerd

patchedDependencies:
  '@nuxthub/core-nightly@0.10.0-20251205-001323-943b30c': patches/@nuxthub__core-nightly.patch
