export const LOCATION_DRAWER_COMPACT_HEIGHT_PX = 450
export const LOCATION_DRAWER_COMPACT_SNAP_POINT = `${LOCATION_DRAWER_COMPACT_HEIGHT_PX}px`
export const LOCATION_DRAWER_EXPANDED_SNAP_POINT = 0.96
export const LOCATION_DRAWER_SNAP_POINTS = [LOCATION_DRAWER_COMPACT_SNAP_POINT, LOCATION_DRAWER_EXPANDED_SNAP_POINT]
export const LOCATION_DRAWER_MAP_BOTTOM_PADDING_PX = LOCATION_DRAWER_COMPACT_HEIGHT_PX
export const LOCATION_DRAWER_EXPANDED_HEIGHT_CSS = 'min(calc(100dvh - env(safe-area-inset-top) - 8px), 96dvh)'
