<script setup lang="ts">
const dummyLocations: LocationDetailResponse[] = [
  {
    uuid: 'test-1',
    name: 'Overnice Creatives',
    address: 'Kreuzbergstr. 28, 10965 Berlin',
    latitude: 52.4934,
    longitude: 13.4014,
    rating: 4.1,
    ratingCount: 135,
    photos: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800', 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800', 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800'],
    gmapsPlaceId: 'test1',
    gmapsUrl: 'https://maps.google.com',
    website: 'https://overnice.com',
    source: 'naka',
    timezone: 'Europe/Berlin',
    openingHours: 'Mo-Fr 09:00-17:00',
    categories: [{ id: 'design_studio', name: 'Design Studio', icon: 'design' }],
    primaryCategory: { id: 'design_studio', name: 'Design Studio', icon: 'design' },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    uuid: 'test-2',
    name: 'La Bella Italia',
    address: 'Via Roma 15, 6900 Lugano',
    latitude: 46.0037,
    longitude: 8.9511,
    rating: 1.4,
    ratingCount: 42,
    photos: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
    gmapsPlaceId: 'test2',
    gmapsUrl: 'https://maps.google.com',
    website: 'https://labellaitalia.ch',
    source: 'naka',
    timezone: 'Europe/Zurich',
    openingHours: 'Mo-Su 11:00-23:00',
    categories: [{ id: 'italian_restaurant', name: 'Italian Restaurant', icon: 'restaurant' }],
    primaryCategory: { id: 'italian_restaurant', name: 'Italian Restaurant', icon: 'restaurant' },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    uuid: 'test-3',
    name: 'Crypto Coffee Hub',
    address: 'Bahnhofstrasse 42, 8001 Zürich',
    latitude: 47.3769,
    longitude: 8.5417,
    rating: 3.5,
    ratingCount: 89,
    photos: ['https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800'],
    gmapsPlaceId: 'test3',
    gmapsUrl: 'https://maps.google.com',
    website: null,
    source: 'naka',
    timezone: 'Europe/Zurich',
    openingHours: 'Mo-Fr 07:00-19:00; Sa 09:00-17:00',
    categories: [{ id: 'coffee_shop', name: 'Coffee Shop', icon: 'cafe' }],
    primaryCategory: { id: 'coffee_shop', name: 'Coffee Shop', icon: 'cafe' },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    uuid: 'test-4',
    name: 'No Rating Place',
    address: 'Unknown Street 1, 12345 City',
    latitude: 47.0,
    longitude: 8.0,
    rating: null,
    ratingCount: null,
    photos: ['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800', 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'],
    gmapsPlaceId: 'test4',
    gmapsUrl: 'https://maps.google.com',
    website: 'https://example.com',
    source: 'naka',
    timezone: 'Europe/Zurich',
    openingHours: null,
    categories: [{ id: 'restaurant', name: 'Restaurant', icon: 'restaurant' }],
    primaryCategory: { id: 'restaurant', name: 'Restaurant', icon: 'restaurant' },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    uuid: 'test-5',
    name: 'Minimal Data Shop',
    address: 'Main St 100, 10000 Town',
    latitude: 46.5,
    longitude: 8.5,
    rating: null,
    ratingCount: null,
    photos: null,
    gmapsPlaceId: 'test5',
    gmapsUrl: 'https://maps.google.com',
    website: null,
    source: 'naka',
    timezone: 'Europe/Zurich',
    openingHours: null,
    categories: [],
    primaryCategory: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    uuid: 'test-6',
    name: 'High Rated Spa',
    address: 'Wellness Alley 5, 6000 Luzern',
    latitude: 47.0502,
    longitude: 8.3093,
    rating: 4.8,
    ratingCount: 512,
    photos: ['https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800', 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800', 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800'],
    gmapsPlaceId: 'test6',
    gmapsUrl: 'https://maps.google.com',
    website: 'https://highrated-spa.ch',
    source: 'naka',
    timezone: 'Europe/Zurich',
    openingHours: 'Mo-Su 10:00-22:00',
    categories: [{ id: 'spa', name: 'Spa', icon: 'spa' }],
    primaryCategory: { id: 'spa', name: 'Spa', icon: 'spa' },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
</script>

<template>
  <div grid="~ cols-1 md:cols-2 lg:cols-3" p-4 bg-neutral-100 gap-4 min-h-screen>
    <div v-for="loc in dummyLocations" :key="loc.uuid" flex="~ col" border="~ neutral-200" pt-128 rounded-8 bg-darkblue bg-neutral-300 h-600 of-hidden shadow-sm>
      <!-- Drawer content -->
      <div f-rounded-t-2xl flex-1 overflow-hidden>
        <LocationDrawerContent :location="loc" :is-expanded="true" />
      </div>
    </div>
  </div>
</template>
